.github/workflows/continous-integration-workflow.yaml
CHANGELOG.md
package-lock.json
package.json
sandbox/package-lock.json
sandbox/package.json

Updated dependencies version, details in change log

Apm 399 increase dependencies version

---

.github/workflows/pr-lint.yaml
azure-pipelines.yml

Add azure-pipelines.yml and update lint regex

---

.flake8
.github/workflows/continous-integration-workflow.yaml
proxies/live/apiproxy/policies/Oauth-VerifyAccessToken.xml
proxies/sandbox/apiproxy/policies/Oauth-VerifyAccessToken.xml
specification-release/apigee_client.py
specification-release/poetry.lock
specification-release/pyproject.toml
specification-release/spec_uploader.py
specification/hello-world.yaml

Amb 11 update the o auth scope

---

specification/hello-world.yaml

Amb 1 remove api key in docs

---

terraform/main.tf

AMB-2 set make_api_product to true

---

.github/workflows/continous-integration-workflow.yaml
CHANGELOG.md
azure-pipelines.yml

* Replace invalid characters in branch name
* Fix dependancy error in build

APM-647 Replace invalid characters in branch name and fix dependancy error 

---

azure-pipelines.yml
proxies/live/apiproxy/proxies/default.xml
proxies/sandbox/apiproxy/proxies/default.xml
specification/hello-world.yaml
terraform/main.tf

Amb 35 latest changes

---

README.md
package.json
sandbox/package.json
specification/hello-world.yaml
terraform/main.tf
tests/package.json

AMB-49 Fixed general mistakes

---

proxies/sandbox/apiproxy/proxies/default.xml
terraform/variables.tf
tests/e2e/hello-world-sandbox.json

Amb 60 add auth and response to status endpoint

---

terraform/variables.tf

AMB-51 remove default values for statuscake

---

terraform/main.tf
terraform/variables.tf

AMB-60 add apikey var for statuscake

---

specification/hello-world.yaml

AMB-53-initial-draft-of-spec

---

specification/hello-world.yaml

AMB-53 | amend endpoint paths

---

specification/hello-world.yaml

AMB-53 fixes to hello-world spec

---

tests/e2e/globals.js

AMB-73 added retry function

---

terraform/main.tf
terraform/variables.tf

AMB-52 remove statuscake

---

specification/hello-world.yaml

AMB-53 update base_url and broken links

---

.flake8
.gitignore
Makefile
azure-pipelines.yml
docker/hello-world-sandbox/Dockerfile

Amb 137 migration tech debt

---

terraform/main.tf

apm-1183: deploy api product in sandbox environments

---

.flake8
tests/e2e/globals.js
tests/package-lock.json
tests/package.json

AMB-138 change globals.js to match with current login page structure

---

azure-pipelines.yml
specification/hello-world.yaml

AMB-220 corrected broken links

---

azure/project.yml

Remove API Product description

---

proxies/live/apiproxy/proxies/default.xml

* Add missing CORS to fault rule

APM-1318 Add missing CORS

---

azure/azure-release-pipeline.yml

explicit api product availability

---

.github/workflows/pr-lint.yaml
Makefile
azure/azure-build-pipeline.yml
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml

apm-1552: revert pinning of utils branch

---

.gitignore
proxies/live/apiproxy/policies/AssignMessage.AddPayloadToPing.xml
tests/e2e/hello-world.collection.json

Amb 457 add content type to ping

---

CHANGELOG.md
package.json
poetry.lock
pyproject.toml
scripts/check_python_licenses.sh
tests/performance/README.md
tests/performance/common/auth.py
tests/performance/locustfile.py

* For testing zero-deployment-time

APM-1270 Zero-Downtime-Deployment-Spike

---

specification/hello-world.yaml

Amb 420 update helloworld spec text

---

proxies/live/apiproxy/proxies/default.xml

APM-468 bugfix - put back apikey auth for hello/application endpoint

---

azure/azure-pr-pipeline.yml
manifest_template.yml

-------
Add manifest_template.yml to control product/spec/api catalog entries.

APM-1572 Add manifest_template.yml

---

proxies/live/apiproxy/policies/FlowCallout.LogToSplunk.xml
proxies/live/apiproxy/proxies/default.xml

amb-101: enable splunk logging

---

azure/azure-release-pipeline.yml

APM-2096 remove monitoring key from release secret ids

---

azure/azure-release-pipeline.yml

Added ASID requirement to internal-dev for testing

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
docker/hello-world-sandbox/package-lock.json
package-lock.json
proxies/live/apiproxy/policies/FlowCallout.GenericAsid.xml
proxies/live/apiproxy/targets/apim.xml
tests/package-lock.json

Added Generic ASID hook

---

proxies/live/apiproxy/proxies/default.xml
proxies/live/apiproxy/targets/apim.xml

Moved shared flow hook to different section

---

proxies/live/apiproxy/proxies/default.xml
proxies/live/apiproxy/targets/apim.xml

Moved GenericAsid flow to preflow request

---

azure/azure-release-pipeline.yml

Removed ASID requirement flag from all environments

---

azure/azure-release-pipeline.yml

Apm 2432 test shared asid flow

---

specification/hello-world.yaml

Added header under parameters for App & user restricted endpoints

---

poetry.lock
pyproject.toml
specification/hello-world.yaml

Apm 3060 fix pip license issue

---

specification/hello-world.yaml

Changes the IPB tag to make-learning-easier

---

specification/hello-world.yaml

Add api status

---

specification/hello-world.yaml

Update spec info to bring hello world to bronze level

AMB-1147: Update spec info to bring hello world to bronze level

---

api_tests/makefile
azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/tests.yml

AMB-1161 run tests on sandbox deployment

---

azure/azure-pr-pipeline.yml
azure/azure-release-pipeline.yml
azure/templates/tests.yml

AMB-1161 run tests during sandbox release

---

README.md

AMB-000 update readme

---

.gitignore
Makefile
api_tests/conftest.py
api_tests/makefile
api_tests/scenarios/test_endpoints.py
proxies/live/apiproxy/policies/OAuthV2.VerifyAccessToken.xml
proxies/live/apiproxy/proxies/default.xml
pyproject.toml

AMB-1224 add application restricted

---

specification/hello-world.yaml

Update spec with app restricted signed jwt auth 

AMB-1228: Update app restricted spec

---

.github/workflows/spec-release-pipeline.yml
specification/hello-world.yaml

APM-3001 add headers to app restricted

---

specification/hello-world.yaml

Smartcards and HSCN access - clarification
* [] Dev

Smartcards and HSCN access - clarification

---

specification/hello-world.yaml

AMP-000 AMP-941 API Specs - add Errors section

---

.github/workflows/spec-release-pipeline.yml
README.md

Apm 3703 fix pipeline

---

.github/workflows/spec-release-pipeline.yml

Fix race conditions

---

.github/workflows/spec-release-pipeline.yml

Update spec command for newer proxygen cli

---

specification/hello-world.yaml

Remove .yaml from server url

---

tests/test_wait_for_status_and_ping.py

Fix tests II

---

.github/proxygen-credentials-template.yaml
.github/workflows/apigee-release-pipeline.yml
.github/workflows/spec-release-pipeline.yml

APM-4116. Add KID to the config template and pipeline variables.

---

.github/workflows/spec-release-pipeline.yml

APM-4116. Bumped Python to 3.9 for the spec release pipeline.

---

package-lock.json
package.json

removed speccy/newman dependencies and addded openapi-generator

---

poetry.lock
pyproject.toml
specification/hello-world.yaml
tests/test_api.py

APM-4646: Correct the Hello World server

---

.github/workflows/apigee-release-pipeline.yml

APM-4459 cat spec file

---

package-lock.json
package.json
poetry.lock
pyproject.toml

npm updates

---

docker/hello-world-sandbox/package-lock.json

update express in package-lock.json

---

.github/workflows/sbom.yml
scripts/create-sbom.sh
scripts/update-sbom.py

sbom configuraiton
